import 'package:flutter_test/flutter_test.dart';
import 'package:seguridad_vial_app/services/actividad_narrativa_template_service.dart';

void main() {
  group('ActividadNarrativaTemplateService', () {
    test('builds a tailored abanderamiento narrative', () {
      final narrativa = ActividadNarrativaTemplateService.build(
        categoriaNombre: 'ABANDERAMIENTOS',
        subcategoriaNombre: 'Hecho de transito',
        lugar: 'Curvas Casa Michoacan',
        municipio: 'MORELIA',
      );

      expect(narrativa, contains('proteccion y abanderamiento'));
      expect(narrativa, contains('hecho de transito'));
      expect(narrativa, contains('Curvas Casa Michoacan'));
      expect(narrativa, contains('MORELIA'));
    });

    test('builds a C5i report narrative', () {
      final narrativa = ActividadNarrativaTemplateService.build(
        categoriaNombre: 'REPORTES C5I',
        subcategoriaNombre: 'Semaforo danado',
        lugar: 'Calzada La Huerta',
        municipio: 'MORELIA',
      );

      expect(narrativa, contains('reporte de base de radio C5i'));
      expect(narrativa, contains('se verifica la situacion'));
      expect(narrativa, contains('semaforo danado'));
    });

    test('builds a fomento-specific narrative', () {
      final narrativa = ActividadNarrativaTemplateService.build(
        categoriaNombre: 'CAPACITACIONES',
        subcategoriaNombre: 'Taller de educacion vial',
        municipio: 'PATZCUARO',
        requiereFomentoCulturaVial: true,
      );

      expect(narrativa, contains('fomento a la cultura vial'));
      expect(narrativa, contains('educacion vial'));
      expect(narrativa, contains('poblacion atendida'));
      expect(narrativa, contains('PATZCUARO'));
    });

    test('varies the narrative when the subcategory changes', () {
      final dispositivo = ActividadNarrativaTemplateService.build(
        categoriaNombre: 'DISPOSITIVOS',
        subcategoriaNombre: 'Escuela segura',
      );
      final monitoreo = ActividadNarrativaTemplateService.build(
        categoriaNombre: 'MONITOREOS',
        subcategoriaNombre: 'Monitoreo de carreteras',
      );

      expect(dispositivo, isNot(monitoreo));
      expect(dispositivo, contains('escuela segura'));
      expect(monitoreo, contains('monitoreo de carreteras'));
    });

    test('keeps pedestrian devices out of fomento templates', () {
      final narrativa = ActividadNarrativaTemplateService.build(
        categoriaNombre: 'DISPOSITIVOS',
        subcategoriaNombre: 'Paso peatonal',
      );

      expect(narrativa, contains('dispositivo de vialidad'));
      expect(narrativa, isNot(contains('fomento a la cultura vial')));
    });

    test('prioritizes road work wording before generic device wording', () {
      final narrativa = ActividadNarrativaTemplateService.build(
        categoriaNombre: 'DISPOSITIVOS',
        subcategoriaNombre: 'Dispositivo por balizamiento',
      );

      expect(narrativa, contains('trabajos relacionados'));
      expect(narrativa, contains('balizamiento'));
    });

    test('adds the operational group when supplied', () {
      final narrativa = ActividadNarrativaTemplateService.build(
        categoriaNombre: 'MONITOREOS',
        subcategoriaNombre: 'Recorrido preventivo',
        operationalGroupLabel: 'CRP / Deltas',
      );

      expect(narrativa, contains('CRP / Deltas'));
      expect(narrativa, isNot(contains('Fenix / Pie Tierra')));
    });

    test('recognizes old prefilled narratives as replaceable templates', () {
      expect(
        ActividadNarrativaTemplateService.looksAutoGenerated(
          'Reporte Fénix / Pie Tierra: Paso peatonal',
        ),
        isTrue,
      );
      expect(
        ActividadNarrativaTemplateService.looksAutoGenerated(
          'Narrativa capturada manualmente por el usuario.',
        ),
        isFalse,
      );
    });
  });
}
