import 'actividad_narrativas.dart';

class ActividadNarrativaTemplateService {
  const ActividadNarrativaTemplateService._();

  static String build({
    required String categoriaNombre,
    required String? subcategoriaNombre,
    String? lugar,
    String? municipio,
    String? operationalGroupLabel,
    bool usarNarrativaFomentoCulturaVial = false,
  }) {
    final categoria = _clean(categoriaNombre);
    final subcategoria = _clean(subcategoriaNombre);
    final descriptor = _descriptor(categoria, subcategoria);
    final location = _locationPhrase(lugar: lugar, municipio: municipio);
    final groupSentence = _operationalGroupSentence(operationalGroupLabel);
    final normalizedCategoria = _normalized(categoria);
    final normalizedSubcategoria = _normalized(subcategoria);
    final text = _normalized('$categoria $subcategoria');

    final definition = _definitionFor(
      normalizedCategoria: normalizedCategoria,
      normalizedSubcategoria: normalizedSubcategoria,
      usarNarrativaFomentoCulturaVial: usarNarrativaFomentoCulturaVial,
    );

    return _render(
      definition,
      descriptor: descriptor,
      location: location,
      operationalGroup: groupSentence,
      closing: _closingFor(text),
      categoria: _sentenceLabel(categoria, fallback: 'actividades'),
    );
  }

  static bool looksAutoGenerated(String? value) {
    final text = _normalized(value ?? '');
    if (text.isEmpty) return false;

    return _containsAny(
      text,
      ActividadNarrativas.marcadoresDeNarrativaAutomatica,
    );
  }

  static ActividadNarrativaDefinition _definitionFor({
    required String normalizedCategoria,
    required String normalizedSubcategoria,
    required bool usarNarrativaFomentoCulturaVial,
  }) {
    final fomento = ActividadNarrativas.fomentoCulturaVial;
    if (usarNarrativaFomentoCulturaVial) {
      return fomento;
    }

    // Algunas categorias representan un origen de reporte que debe conservar
    // su redaccion aunque la subcategoria comparta palabras con otra regla.
    for (final definition in ActividadNarrativas.porCategoriaOSubcategoria) {
      if (definition.priorizarCoincidenciaDeCategoria &&
          _containsAny(normalizedCategoria, definition.palabrasClave)) {
        return definition;
      }
    }

    // La subcategoria describe la actividad concreta. Se revisa antes que la
    // categoria para que, por ejemplo, PATRULLAJE dentro de DISPOSITIVOS no
    // cargue el texto generico de apoyo al paso peatonal.
    for (final definition in ActividadNarrativas.porCategoriaOSubcategoria) {
      if (_containsAny(normalizedSubcategoria, definition.palabrasClave)) {
        return definition;
      }
    }

    for (final definition in ActividadNarrativas.porCategoriaOSubcategoria) {
      if (_containsAny(normalizedCategoria, definition.palabrasClave)) {
        return definition;
      }
    }

    return ActividadNarrativas.predeterminada;
  }

  static String _render(
    ActividadNarrativaDefinition definition, {
    required String descriptor,
    required String location,
    required String operationalGroup,
    required String closing,
    required String categoria,
  }) {
    return _joinSentences(
      definition.parrafos
          .map((paragraph) {
            return paragraph
                .replaceAll('{descriptor}', descriptor)
                .replaceAll('{location}', location)
                .replaceAll('{operationalGroup}', operationalGroup)
                .replaceAll('{closing}', closing)
                .replaceAll('{categoria}', categoria);
          })
          .toList(growable: false),
    );
  }

  static String _descriptor(String categoria, String subcategoria) {
    final sub = _sentenceLabel(subcategoria);
    if (sub.isNotEmpty) {
      return sub;
    }

    final cat = _sentenceLabel(categoria);
    if (cat.isNotEmpty) {
      return cat;
    }

    return 'la actividad registrada';
  }

  static String _locationPhrase({String? lugar, String? municipio}) {
    final cleanLugar = _clean(lugar);
    final cleanMunicipio = _clean(municipio);

    if (cleanLugar.isNotEmpty && cleanMunicipio.isNotEmpty) {
      return 'en $cleanLugar, municipio de $cleanMunicipio';
    }
    if (cleanLugar.isNotEmpty) {
      return 'en $cleanLugar';
    }
    if (cleanMunicipio.isNotEmpty) {
      return 'en el municipio de $cleanMunicipio';
    }
    return 'en el lugar registrado';
  }

  static String _operationalGroupSentence(String? operationalGroupLabel) {
    final group = _clean(operationalGroupLabel);
    if (group.isEmpty) return '';
    return 'Interviene personal de $group para dar seguimiento al servicio.';
  }

  static String _closingFor(String normalizedText) {
    if (_containsAny(normalizedText, const [
      'CONCLUYE',
      'FINALIZA',
      'TERMINA',
      'SE RETIRA',
      'LIBERA CIRCULACION',
    ])) {
      return 'La actividad concluye sin novedad relevante que reportar, anexando evidencia fotografica para conocimiento de la superioridad.';
    }

    return 'Se queda pendiente de informar cualquier novedad relevante, anexando evidencia fotografica para conocimiento de la superioridad.';
  }

  static String _sentenceLabel(String value, {String fallback = ''}) {
    final clean = _clean(value);
    if (clean.isEmpty) {
      return fallback;
    }
    return clean.toLowerCase().replaceAll(RegExp(r'\s+'), ' ');
  }

  static bool _containsAny(String text, List<String> needles) {
    for (final needle in needles) {
      if (text.contains(_normalized(needle))) {
        return true;
      }
    }
    return false;
  }

  static String _normalized(String value) {
    const accents = <String, String>{
      'Á': 'A',
      'É': 'E',
      'Í': 'I',
      'Ó': 'O',
      'Ú': 'U',
      'Ü': 'U',
      'Ñ': 'N',
      'á': 'A',
      'é': 'E',
      'í': 'I',
      'ó': 'O',
      'ú': 'U',
      'ü': 'U',
      'ñ': 'N',
    };

    final buffer = StringBuffer();
    for (final char in value.trim().split('')) {
      buffer.write(accents[char] ?? char.toUpperCase());
    }
    return buffer.toString().replaceAll(RegExp(r'\s+'), ' ');
  }

  static String _joinSentences(List<String> sentences) {
    return sentences
        .map((sentence) => sentence.trim())
        .where((sentence) => sentence.isNotEmpty)
        .join('\n\n');
  }

  static String _clean(String? value) {
    return (value ?? '').trim().replaceAll(RegExp(r'\s+'), ' ');
  }
}
