// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGE0lvpOvzn1k-batNrQdf_z6mVOSrHwQ',
    appId: '1:846104355430:web:ed89789bc07b5633b8c3a7',
    messagingSenderId: '846104355430',
    projectId: 'seguridad-64036',
    authDomain: 'seguridad-64036.firebaseapp.com',
    storageBucket: 'seguridad-64036.firebasestorage.app',
    measurementId: 'G-QCWEMW6Z1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeOS9ql1gjtNWBgrnx4sZ1kIT0GrIRog',
    appId: '1:846104355430:android:955a6b1a7500589fb8c3a7',
    messagingSenderId: '846104355430',
    projectId: 'seguridad-64036',
    storageBucket: 'seguridad-64036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-yAiXBhFImQ4vZnmKhEaO1Mqc1xhCffA',
    appId: '1:846104355430:ios:8ad8584bd5bc2c16b8c3a7',
    messagingSenderId: '846104355430',
    projectId: 'seguridad-64036',
    storageBucket: 'seguridad-64036.firebasestorage.app',
    iosBundleId: 'com.nasaka.seguridadvial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-yAiXBhFImQ4vZnmKhEaO1Mqc1xhCffA',
    appId: '1:846104355430:ios:48018ca6021008f9b8c3a7',
    messagingSenderId: '846104355430',
    projectId: 'seguridad-64036',
    storageBucket: 'seguridad-64036.firebasestorage.app',
    iosBundleId: 'com.example.seguridadVialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGE0lvpOvzn1k-batNrQdf_z6mVOSrHwQ',
    appId: '1:846104355430:web:4007050544de11f4b8c3a7',
    messagingSenderId: '846104355430',
    projectId: 'seguridad-64036',
    authDomain: 'seguridad-64036.firebaseapp.com',
    storageBucket: 'seguridad-64036.firebasestorage.app',
    measurementId: 'G-EVPH2957B9',
  );
}
